/**
 * STORE
 */
export const GET_ALL_STORES = 'GET_ALL_STORES';
export const FAIL_TO_GET_STORES = 'FAIL_TO_GET_STORES';
export const FETCH_STORE_BY_ID = 'FETCH_STORE_BY_ID';
export const SEARCH_STORE_BY_ADD_INFOR = 'SEARCH_STORE_BY_ADD_INFOR';
export const GET_NEARBY_STORES = 'GET_NEARBY_STORES';

/**
 * LOGIN
 */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';

/**
 * SEARCHBOX
 */
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const UNTOGGLE_SEARCH = 'UNTOGGLE_SEARCH';

/**
 * CART_USER
 */
export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const UPDATE_ITEM_IN_CART = 'UPDATE_ITEM_IN_CART';
export const CANCEL_CHECKOUT = 'CANCEL_CHECKOUT';
export const GET_CHECKOUT_CART = 'GET_CHECKOUT_CART';
export const DELETE_ITEM_IN_CART = 'DELETE_ITEM_IN_CART';

/**
 * VEGETABLE
 */
export const GET_ALL_VEGETABLES = 'GET_ALL_VEGETABLES';
export const GET_CURRENT_MENU = 'GET_CURRENT_MENU';
export const ADD_ITEM_TO_MENU = 'ADD_ITEM_TO_MENU';
export const UPDATE_MENU = 'UPDATE_MENU';
export const GET_COMPATIBLE_STORES = 'GET_COMPATIBLE_STORES';

/**
 * NETWORK
 */
export const CHANGE_CONNECTION_STATUS = 'CHANGE_CONNECTION_STATUS';


